// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clinics.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createClinic = `-- name: CreateClinic :one
INSERT INTO clinics (id, person_id)
VALUES ($1::uuid, $2::uuid)
RETURNING id, person_id, created_at, updated_at, deleted_at
`

type CreateClinicParams struct {
	ID       string `json:"id"`
	PersonID string `json:"person_id"`
}

func (q *Queries) CreateClinic(ctx context.Context, arg CreateClinicParams) (Clinic, error) {
	row := q.db.QueryRowContext(ctx, createClinic, arg.ID, arg.PersonID)
	var i Clinic
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteClinic = `-- name: DeleteClinic :execrows
UPDATE clinics
SET deleted_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1::uuid
  AND deleted_at IS NULL
`

func (q *Queries) DeleteClinic(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteClinic, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getClinicByID = `-- name: GetClinicByID :one
SELECT id, person_id, created_at, updated_at, deleted_at
FROM clinics
WHERE id = $1::uuid
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetClinicByID(ctx context.Context, id string) (Clinic, error) {
	row := q.db.QueryRowContext(ctx, getClinicByID, id)
	var i Clinic
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getClinicDetails = `-- name: GetClinicDetails :one
SELECT
    c.id AS clinic_id,
    c.person_id,
    p.legal_name,
    p.trade_name,
    p.tax_id_number,
    p.email,
    p.phone
FROM clinics c
JOIN people p ON p.id = c.person_id
WHERE c.id = $1::uuid
  AND c.deleted_at IS NULL
  AND p.deleted_at IS NULL
LIMIT 1
`

type GetClinicDetailsRow struct {
	ClinicID    string         `json:"clinic_id"`
	PersonID    string         `json:"person_id"`
	LegalName   string         `json:"legal_name"`
	TradeName   sql.NullString `json:"trade_name"`
	TaxIDNumber string         `json:"tax_id_number"`
	Email       sql.NullString `json:"email"`
	Phone       sql.NullString `json:"phone"`
}

func (q *Queries) GetClinicDetails(ctx context.Context, id string) (GetClinicDetailsRow, error) {
	row := q.db.QueryRowContext(ctx, getClinicDetails, id)
	var i GetClinicDetailsRow
	err := row.Scan(
		&i.ClinicID,
		&i.PersonID,
		&i.LegalName,
		&i.TradeName,
		&i.TaxIDNumber,
		&i.Email,
		&i.Phone,
	)
	return i, err
}

const listClinicDetailsCursor = `-- name: ListClinicDetailsCursor :many
SELECT
    c.id AS clinic_id,
    c.person_id,
    p.legal_name,
    p.trade_name,
    p.tax_id_number,
    p.email,
    p.phone
FROM clinics c
JOIN people p ON p.id = c.person_id
WHERE c.deleted_at IS NULL
  AND p.deleted_at IS NULL
  AND ($1::uuid IS NULL OR c.id > $1::uuid)
ORDER BY c.id
LIMIT $2
`

type ListClinicDetailsCursorParams struct {
	AfterID   uuid.NullUUID `json:"after_id"`
	PageLimit int32         `json:"page_limit"`
}

type ListClinicDetailsCursorRow struct {
	ClinicID    string         `json:"clinic_id"`
	PersonID    string         `json:"person_id"`
	LegalName   string         `json:"legal_name"`
	TradeName   sql.NullString `json:"trade_name"`
	TaxIDNumber string         `json:"tax_id_number"`
	Email       sql.NullString `json:"email"`
	Phone       sql.NullString `json:"phone"`
}

func (q *Queries) ListClinicDetailsCursor(ctx context.Context, arg ListClinicDetailsCursorParams) ([]ListClinicDetailsCursorRow, error) {
	rows, err := q.db.QueryContext(ctx, listClinicDetailsCursor, arg.AfterID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClinicDetailsCursorRow{}
	for rows.Next() {
		var i ListClinicDetailsCursorRow
		if err := rows.Scan(
			&i.ClinicID,
			&i.PersonID,
			&i.LegalName,
			&i.TradeName,
			&i.TaxIDNumber,
			&i.Email,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
