// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
	"time"
)

type BankAccount struct {
	ID            string       `json:"id"`
	ClinicID      string       `json:"clinic_id"`
	BankCode      string       `json:"bank_code"`
	BranchNumber  string       `json:"branch_number"`
	AccountNumber string       `json:"account_number"`
	CreatedAt     time.Time    `json:"created_at"`
	UpdatedAt     time.Time    `json:"updated_at"`
	DeletedAt     sql.NullTime `json:"deleted_at"`
}

type Clinic struct {
	ID        string       `json:"id"`
	PersonID  string       `json:"person_id"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type ClinicDentist struct {
	ClinicID              string       `json:"clinic_id"`
	DentistID             string       `json:"dentist_id"`
	IsAdmin               bool         `json:"is_admin"`
	IsLegalRepresentative bool         `json:"is_legal_representative"`
	StartedAt             time.Time    `json:"started_at"`
	EndedAt               sql.NullTime `json:"ended_at"`
	CreatedAt             time.Time    `json:"created_at"`
	UpdatedAt             time.Time    `json:"updated_at"`
}

type Dentist struct {
	ID        string       `json:"id"`
	PersonID  string       `json:"person_id"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type Person struct {
	ID          string         `json:"id"`
	PersonType  string         `json:"person_type"`
	TaxIDType   string         `json:"tax_id_type"`
	TaxIDNumber string         `json:"tax_id_number"`
	LegalName   string         `json:"legal_name"`
	TradeName   sql.NullString `json:"trade_name"`
	Email       sql.NullString `json:"email"`
	Phone       sql.NullString `json:"phone"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
}

type User struct {
	ID           string       `json:"id"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
}
