// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"
)

type Querier interface {
	CountActiveClinicLinksByDentist(ctx context.Context, dentistID string) (int64, error)
	CreateBankAccount(ctx context.Context, arg CreateBankAccountParams) (BankAccount, error)
	CreateClinic(ctx context.Context, arg CreateClinicParams) (Clinic, error)
	CreateClinicDentist(ctx context.Context, arg CreateClinicDentistParams) (ClinicDentist, error)
	CreateDentist(ctx context.Context, arg CreateDentistParams) (Dentist, error)
	CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBankAccountByIDAndClinicID(ctx context.Context, arg DeleteBankAccountByIDAndClinicIDParams) (int64, error)
	DeleteClinic(ctx context.Context, id string) (int64, error)
	DeleteDentist(ctx context.Context, id string) (int64, error)
	DeletePerson(ctx context.Context, id string) (int64, error)
	EndClinicDentist(ctx context.Context, arg EndClinicDentistParams) (int64, error)
	EndClinicDentistsByClinic(ctx context.Context, clinicID string) (int64, error)
	EndClinicDentistsByDentist(ctx context.Context, dentistID string) (int64, error)
	GetActiveClinicDentist(ctx context.Context, arg GetActiveClinicDentistParams) (ClinicDentist, error)
	GetBankAccountByIDAndClinicID(ctx context.Context, arg GetBankAccountByIDAndClinicIDParams) (BankAccount, error)
	GetClinicByID(ctx context.Context, id string) (Clinic, error)
	GetClinicDetails(ctx context.Context, id string) (GetClinicDetailsRow, error)
	GetDentistByID(ctx context.Context, id string) (Dentist, error)
	GetDentistByPersonID(ctx context.Context, personID string) (Dentist, error)
	GetDentistDetailsByID(ctx context.Context, id string) (GetDentistDetailsByIDRow, error)
	GetPersonByTaxID(ctx context.Context, taxIDNumber string) (Person, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListBankAccountsByClinicID(ctx context.Context, clinicID string) ([]BankAccount, error)
	ListClinicDetailsCursor(ctx context.Context, arg ListClinicDetailsCursorParams) ([]ListClinicDetailsCursorRow, error)
	ListDentistsByClinicID(ctx context.Context, clinicID string) ([]ListDentistsByClinicIDRow, error)
	ListDentistsByClinicIDCursor(ctx context.Context, arg ListDentistsByClinicIDCursorParams) ([]ListDentistsByClinicIDCursorRow, error)
	ListDentistsByClinicIDs(ctx context.Context, clinicIds []string) ([]ListDentistsByClinicIDsRow, error)
	UpdateClinicDentistRole(ctx context.Context, arg UpdateClinicDentistRoleParams) (ClinicDentist, error)
	UpdatePerson(ctx context.Context, arg UpdatePersonParams) (Person, error)
}

var _ Querier = (*Queries)(nil)
